/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminBotActions: typeof import('./src/components/AdminBotActions.vue')['default']
    AdminBotRow: typeof import('./src/components/AdminBotRow.vue')['default']
    AdminBotTradingActions: typeof import('./src/components/AdminBotTradingActions.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Bot: typeof import('./src/components/Bot.vue')['default']
    BotActions: typeof import('./src/components/BotActions.vue')['default']
    BotBrand: typeof import('./src/components/BotBrand.vue')['default']
    BotCard: typeof import('./src/components/BotCard.vue')['default']
    BotConfig: typeof import('./src/components/BotConfig.vue')['default']
    BotConfigManager: typeof import('./src/components/BotConfigManager.vue')['default']
    BotCursor: typeof import('./src/components/BotCursor.vue')['default']
    BotDropProfileTable: typeof import('./src/components/BotDropProfileTable.vue')['default']
    BotPositionSlider: typeof import('./src/components/BotPositionSlider.vue')['default']
    BotRow: typeof import('./src/components/BotRow.vue')['default']
    BotTradingActions: typeof import('./src/components/BotTradingActions.vue')['default']
    ConfirmationPopup: typeof import('./src/components/ConfirmationPopup.vue')['default']
    CryptoSnowfall: typeof import('./src/components/CryptoSnowfall.vue')['default']
    Exchange: typeof import('./src/components/Exchange.vue')['default']
    HelpDialog: typeof import('./src/components/HelpDialog.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    LogList: typeof import('./src/components/LogList.vue')['default']
    MiniChart: typeof import('./src/components/MiniChart.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TradingBalances: typeof import('./src/components/TradingBalances.vue')['default']
    TradingView: typeof import('./src/components/TradingView.vue')['default']
    TransactionList: typeof import('./src/components/TransactionList.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
  }
}
