/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account': RouteRecordInfo<
      '/account',
      '/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/bots': RouteRecordInfo<
      '/admin/bots',
      '/admin/bots',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/logs': RouteRecordInfo<
      '/admin/logs',
      '/admin/logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/users': RouteRecordInfo<
      '/admin/users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/balances': RouteRecordInfo<
      '/balances',
      '/balances',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bots/': RouteRecordInfo<
      '/bots/',
      '/bots',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bots/new': RouteRecordInfo<
      '/bots/new',
      '/bots/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cryptos': RouteRecordInfo<
      '/cryptos',
      '/cryptos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/favorites': RouteRecordInfo<
      '/favorites',
      '/favorites',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home': RouteRecordInfo<
      '/home',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/logout': RouteRecordInfo<
      '/logout',
      '/logout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/news': RouteRecordInfo<
      '/news',
      '/news',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register': RouteRecordInfo<
      '/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/trading': RouteRecordInfo<
      '/trading',
      '/trading',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/account.vue': {
      routes:
        | '/account'
      views:
        | never
    }
    'src/pages/admin/bots.vue': {
      routes:
        | '/admin/bots'
      views:
        | never
    }
    'src/pages/admin/logs.vue': {
      routes:
        | '/admin/logs'
      views:
        | never
    }
    'src/pages/admin/users.vue': {
      routes:
        | '/admin/users'
      views:
        | never
    }
    'src/pages/balances.vue': {
      routes:
        | '/balances'
      views:
        | never
    }
    'src/pages/bots/index.vue': {
      routes:
        | '/bots/'
      views:
        | never
    }
    'src/pages/bots/new.vue': {
      routes:
        | '/bots/new'
      views:
        | never
    }
    'src/pages/cryptos.vue': {
      routes:
        | '/cryptos'
      views:
        | never
    }
    'src/pages/favorites.vue': {
      routes:
        | '/favorites'
      views:
        | never
    }
    'src/pages/home.vue': {
      routes:
        | '/home'
      views:
        | never
    }
    'src/pages/logout.vue': {
      routes:
        | '/logout'
      views:
        | never
    }
    'src/pages/news.vue': {
      routes:
        | '/news'
      views:
        | never
    }
    'src/pages/register.vue': {
      routes:
        | '/register'
      views:
        | never
    }
    'src/pages/trading.vue': {
      routes:
        | '/trading'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
